### ISSUE TITLE
Add Django Rest Framework generator

### ISSUE THREAD

**Issue by teolemon** [mmcardle/django_builder#1]
First a huge thank you, the app is just great. It would have saved me a lot of time, had I seen it a year ago ;)

Having some kind of Django Rest Framework support would be great, for people building Mobile Apps or AngularJS apps.

**Comment by mmcardle** [comment]
Thats a good idea, do you have any boiler plate code for this? I have never used DRF myself so any pointers welcome.

**Comment by teolemon** [comment]
I have made some code, but I haven't tested it in real life, so it's hard to propose it.
In addition to the extensive documentation, there's a repo with the source code example of the tutorial (that I followed)
https://github.com/tomchristie/rest-framework-tutorial

**Comment by mmcardle** [comment]
Have added some simple api.py and serializers.py modules.
