### ISSUE TITLE
Archive type is not supported

### ISSUE THREAD

**Issue by primoz-k** [mmcardle/django_builder#10]
Hi,
I'm having problems with opening downloaded archive, because it throws "Archive type is not supported".

Am I doing something wrong? How do you extract downloaded file?

I'm using Ubuntu 14.04.

**Comment by marklyon** [comment]
You may need to rename the downloaded file with a .tar extension.  I am then able to successfully open using [7-Zip](http://www.7-zip.org/) on Windows, though there are plenty of other utilities that can open the [TAR](http://linuxcommand.org/man_pages/tar1.html) file.

**Comment by primoz-k** [comment]
Thanks, @marklyon , it works!

Would be cool to fix download file with added `.tar` extension.

**Comment by primoz-k** [comment]
Just checking, @mmcardle , should this be fixed?

**Comment by mmcardle** [comment]
@primoz-k This should be fixed now, it should now download as <app_name>.tar
What browser where you using for the download? I have tested on Chrome and Firefox

**Comment by primoz-k** [comment]
@mmcardle It works now, thank you for the fix.
