### ISSUE TITLE
No migrations made

### ISSUE THREAD

**Issue by dgleba** [mmcardle/django_builder#100]
https://djangobuilder.io/#/project/FJsbPtioNSAqK2SwRXIv

I download this project I made on your site.

I am using it in docker.
```
    docker-compose run --rm djdev python manage.py makemigrations
```

When I do this there are no migrations made for the blog app or the book-app app.

**Comment by mmcardle** [comment]
Hi @dgleba I think `makemigrations` requires you to specifiy the applabel

https://docs.djangoproject.com/en/3.1/ref/django-admin/#django-admin-makemigrations

So in your case it would be 

`docker-compose run --rm djdev python manage.py makemigrations blog book`

Does that work?

**Comment by dgleba** [comment]
You may be right. I didn't try that yet.

I think that `manage.py startapp book` will create a migrations folder and __init.py__ file.

With that `manage.py makemigrations` is all that is necessary. All the necessary migrations will be made.

Can you create that file and folder in your https://djangobuilder.io ?

Thoughts?

**Comment by mmcardle** [comment]
This is now complete
