### ISSUE TITLE
TemplateDoesNotExist blog/post_list.html

### ISSUE THREAD

**Issue by dgleba** [mmcardle/django_builder#101]
I made one model called `book` and one called `Post`.

I am getting errors with the Post model.

The django tutorial Capitalizes model names.  https://docs.djangoproject.com/en/3.1/intro/tutorial02/

What is the correct way forward?

```
Request Method: | GET
-- | --
http://192.168.88.60:6461/blog/blog/Post/
3.1.1
TemplateDoesNotExist
blog/post_list.html
/usr/local/lib/python3.7/site-packages/django/template/loader.py, line 47, in select_template
/usr/local/bin/python
3.7.9
['/code',  '/usr/local/lib/python37.zip',  '/usr/local/lib/python3.7',  '/usr/local/lib/python3.7/lib-dynload',  '/usr/local/lib/python3.7/site-packages']
Sun, 13 Sep 2020 00:10:08 +0000
```

**Comment by mmcardle** [comment]
Hi @dgleba 

I would recommend having capitalised models names, so `Book`.

Then if that does not fix the issues check the values of `TEMPLATES` setting in `settings.py` and make sure `'APP_DIRS': True,`
And check that the file `post_list.html` exists and is readable by your django process.

**Comment by mmcardle** [comment]
Hi @dgleba i think this is a bug.
Thanks for the report

**Comment by mmcardle** [comment]
Fixed
