### ISSUE TITLE
Sorry, Too many models

### ISSUE THREAD

**Issue by dgleba** [mmcardle/django_builder#104]
I have only two projects. Each has two or less models. 

I tried to add post model to blogapp which has only one model - book.
I used the upload button to try to add post model after book model was added by upload.

I get this error. Sorry, you have too many models in this app, maximum is 25.

![image](https://user-images.githubusercontent.com/4622715/95016372-9dbc1000-0620-11eb-8617-eed93a1e6324.png)

**Comment by mmcardle** [comment]
@dgleba I will take a look at this bug
