### ISSUE TITLE
Got two `Book` models when created a new project manually without upload

### ISSUE THREAD

**Issue by dgleba** [mmcardle/django_builder#105]
I just made a new project and added a model `Book` by typing in the name `Book`, not using the upload button.

The picture shows the project name and the two `Book` models.

![image](https://user-images.githubusercontent.com/4622715/95016676-75351580-0622-11eb-91fe-92f5e19b536e.png)

**Comment by mmcardle** [comment]
Hi @dgleba 

Thanks for the report, it might be a bug where the button is not debounced so could be clicked twice in quick succession.
I will check if that might be the case.
