### ISSUE TITLE
Input is erased on validation and there is no book field

### ISSUE THREAD

**Issue by dgleba** [mmcardle/django_builder#107]
I created the blogapp with Post and Book models with a foreign key so that each post could refer to a book.

In the pictures below there are two issues. 

1. The foreign key is required but no field is on the template to create it with a dropdown or anything.

2. When the save button is pressed, the validation message comes up saying book_id is required.  The problem is that all input in fields has been erased.

![2020-10-04 11_47_27-643082186-reded446@ad - AnyDesk](https://user-images.githubusercontent.com/4622715/95020276-27c3a300-0638-11eb-8fa1-8bfeab283d19.jpg)

![2020-10-04 11_47_46-643082186-reded446@ad - AnyDesk](https://user-images.githubusercontent.com/4622715/95020299-4a55bc00-0638-11eb-9605-d67edfe48eb9.jpg)

**Comment by mmcardle** [comment]
@dgleba I will take a look

**Comment by dgleba** [comment]
Are you able to reproduce the problem is that all input in all fields has been erased when the validation message appears?

I have another app that has a javascript popup like the picture below. I can't figure out how to find docs/posts on what drives the difference. They are both modelforms. The views both say 'generic' in them, although they have slightly different imports and syntax. 

![image](https://user-images.githubusercontent.com/4622715/95686884-8fe12e80-0bce-11eb-93a4-706aefc0b9a4.png)
