### ISSUE TITLE
ContentType & GenericForeignKey Support

### ISSUE THREAD

**Issue by jameswyse** [mmcardle/django_builder#11]
Awesome project! 
Just have one small request.. would you consider adding support for contenttypes / generic foreign keys? 

It basically boils down to:

- Add `django.contrib.contenttypes.models.ContentType` to the list of Django models (like the existing `User` and `Group`)
- Add a `GenericForeignKey` relationship type

Thanks!

**Comment by mmcardle** [comment]
Thats a great idea.

Just pushed some code to do this
