### ISSUE TITLE
How to self host without firebase

### ISSUE THREAD

**Issue by azataiot** [mmcardle/django_builder#119]
I really love djangobuilder for building django models, but we have a problem -- in our work environment, we don't access to external data bases ( including firebase ) , we use internal databases hosted in the internal system.

I want to use django_builder, so I wanted to deploy the project internally, but as firebase itself is a google commercial product that dose not give you an option to host it locally, is there any other dbs that djangobuilder support which I can deploy and run in the internal site? 

Thanks!

**Comment by mmcardle** [comment]
Hi @azataiot 

Thanks very much for your comments, It is great to see Django Builder being used.

Yes I have plans for a version 3 of Django Builder, that can be run in a docker setup locally, but I have only just started work on that. It would not use any external services. It you have any comments on what would you would like to see in a new version then let me know.

For now the only option for you might be to use version 1 http://mmcardle.github.io/django_builder/ or the `v1` branch, but this is not as feature complete as version 2 and only stores data in the local browser.

Thanks

**Comment by azataiot** [comment]
> Hi @azataiot
> 
> Thanks very much for your comments, It is great to see Django Builder being used.
> 
> Yes I have plans for a version 3 of Django Builder, that can be run in a docker setup locally, but I have only just started work on that. It would not use any external services. It you have any comments on what would you would like to see in a new version then let me know.
> 
> For now the only option for you might be to use version 1 http://mmcardle.github.io/django_builder/ or the `v1` branch, but this is not as feature complete as version 2 and only stores data in the local browser.
> 
> Thanks

Then I will work on v1 until you have done the docker deployed version of the app. by the way, it is very nice to have an app like django builder, and I think I will also participant in the development process of the django-builder in the near future as soon as I can consume some time on the project.
