### ISSUE TITLE
djangobuilder.io: No text in privacy \ cookies pop-up

### ISSUE THREAD

**Issue by askpatrickw** [mmcardle/django_builder#134]
The privacy pop-up has no text.

iPad Pro (11-inch) (3rd generation)
IOS 15.3
Firefox Daylight 96.0 (7403)

![9EBF0260-16EF-4735-93CF-0BE37D87BE81](https://user-images.githubusercontent.com/4002194/152733524-87224c5a-65bb-4fa4-b1d2-b44500da7c4a.jpeg)

**Comment by mmcardle** [comment]
Thanks @jonashaag 

Should be fixed now with #146

**Comment by askpatrickw** [comment]
looks fixed now
