### ISSUE TITLE
GeoDjango Model API

### ISSUE THREAD

**Issue by nikolaysm** [mmcardle/django_builder#145]
Hi,

Thanks for sharing this great app.

It would be useful to add support for  GeoDjango Model Fields.

[GeoDjango Model API](https://docs.djangoproject.com/en/dev/ref/contrib/gis/model-api/#module-django.contrib.gis.db.models)

**Comment by mmcardle** [comment]
Hi @nikolaysm 

That sounds quite possible, what version/deployment of the app are you using?

**Comment by nikolaysm** [comment]
I am using Django Builder v2.

**Comment by mmcardle** [comment]
Hi @nikolaysm 

Should be fixed now with #146
