### ISSUE TITLE
Django 1.10 support?

### ISSUE THREAD

**Issue by kptac** [mmcardle/django_builder#15]
Hi 

I've used this in the past and its been very helpful. I suggest making it compatible with 1.10. Like urlpatterns, new fields, etc will be a nice addition.

Keep up the good work.

Also, cant find any donate links.

**Comment by mmcardle** [comment]
Hi, that is a great idea.
I haven't any projects that use 1.10 yet, but i'll try to get something going.

I haven't set up any donate page, any recommendations gratipay, patreon?
Thanks

**Comment by kptac** [comment]
I have only used PayPal donations before. Not sure of gratipay or patreon. Message here, whenever you set it up. I can atleast pay for couple of :beers:

**Comment by christophersbrown** [comment]
Just came across this - very helpful and nice idea!  I second the Django 1.10 idea (and the beer idea).

**Comment by mmcardle** [comment]
Going to add the following fields

```
django.db.models.CommaSeparatedIntegerField
django.db.models.BigAutoField
django.db.models.BigIntegerField
django.db.models.DurationField
django.db.models.PositiveSmallIntegerField
django.db.models.SlugField
django.db.models.AutoField
django.db.models.SmallIntegerField
django.db.models.URLField
django.db.models.UUIDField
django.db.models.EmailField
```

and also update the url patterns to 1.10 syntax

```
urlpatterns += (
    url(r'^/$', 'view'),
)
```

Anything else from Django 1.10?

**Comment by kptac** [comment]
Yes this looks good so far, we can start playing with it and add more in the future. I normally use this to visualize my models properly and having all new fields is good so far. 
More features the merrier.

**Comment by christophersbrown** [comment]
Sounds good mmcardle.  You've touched on the things I had noticed.  Thanks for your efforts on this!

**Comment by mmcardle** [comment]
@kptac @christophersbrown 

This is now live on the main site, as well as a Donate button :)

**Comment by kptac** [comment]
well done! Donated. Keep up the good work.
