### ISSUE TITLE
Allow adding relationship to non-app model

### ISSUE THREAD

**Issue by wengole** [mmcardle/django_builder#17]
At the moment it seems you can only add a relationship field to model created in Django Builder, or User or Group (or content types).

I'm trying to create a new app for an existing project and want to add relationships to models in other apps. The UI of Django Builder doesn't allow this.

As far as I can tell, if you could just allow adding a string into that field, that would solve this.

**Comment by mmcardle** [comment]
Hi, Thanks for the feedback.

Yes that sounds like a good suggestion, allowing a relationship to another app would be simple to do, that is how relationships to **auth.User** work.
Ill try to get a change pushed for that.

**Comment by mmcardle** [comment]
Hi I have pushed a change if you want to try it out.

**Comment by wengole** [comment]
Looks good to me :+1: 

Tried it with a couple of things with FKs and M2Ms
