### ISSUE TITLE
Autogenerating the models from a SQL dump

### ISSUE THREAD

**Issue by teolemon** [mmcardle/django_builder#2]
It would be great to do that kind of thing
http://stackoverflow.com/questions/1179469/is-it-posible-to-generate-django-models-from-the-database

**Comment by mmcardle** [comment]
Hi teolemon ,

Now that there is a way to import from a models.py file, could this be achieved with inspectdb then upload the result to django_builder?

**Comment by mmcardle** [comment]
Hi, this can now be achieved by using inspect db

https://docs.djangoproject.com/en/1.10/ref/django-admin/#django-admin-inspectdb

and then importing the models.py generated by this command
