### ISSUE TITLE
Add "Create Project" as a new function

### ISSUE THREAD

**Issue by bradlishman** [mmcardle/django_builder#21]
In addition to creating models, consider adding the ability to create the project too. The .tar downloaded would then be a complete Django project and app.

**Comment by mmcardle** [comment]
This is a great idea, I was considering what 3rd party apps to include in any settings file.
I use a few apps like django-configurations, django-debug-toolbar, django-compressor ... etc etc in my boilerplate settings.

I think it might be better to have no 3rd party apps, and just go for the basic project layout you get with 

`django-admin.py startproject`

thoughts?

**Comment by bradlishman** [comment]
Would be good. Keeping things as vanilla as possible makes sense. Main goal with builder is to automate the boring stuff mostly right?

**Comment by mmcardle** [comment]
Hi i have pushed a change to add some of this functionality
