### ISSUE TITLE
Underscores not showing on modal forms

### ISSUE THREAD

**Issue by bradlishman** [mmcardle/django_builder#22]
![underscores](https://cloud.githubusercontent.com/assets/2871146/20519297/a9ca529e-b0a2-11e6-8938-50fabfbc77c9.png)

**Comment by mmcardle** [comment]
hi @bradlishman 

This might be a display issue
What browser and OS is this? I can't seem to recreate on OSX Safari/Chrome or Firefox

![screen shot 2016-11-25 at 14 53 03](https://cloud.githubusercontent.com/assets/1503478/20628615/eebcf928-b31e-11e6-8109-547f482c3a56.png)

**Comment by bradlishman** [comment]
Chrome on Ubuntu.

**Comment by TeddyBear06** [comment]
Hey @bradlishman,

I also try using Chrome on Ubuntu (Version 55.0.2883.87 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)) and it works well.

![telechargement](https://cloud.githubusercontent.com/assets/1452474/23073923/6e022d84-f537-11e6-8e5c-997acdc1b60e.png)

As @mmcardle said, this might be a display issue.

Try to disable extensions, zoom at 100%, use a standard system font... Whatever can modify the way your browser is rendering things.
