### ISSUE TITLE
Update to Django 1.10.X

### ISSUE THREAD

**Issue by bradlishman** [mmcardle/django_builder#23]
Consider adding support for versions later than 1.7

**Comment by mmcardle** [comment]
Hi @bradlishman 

Yes I would like to update to django 1.10.X project, just haven't had time to do any testing on it.
Do you know of any specific things that don't work in a 1.10.X project?

Thanks,

**Comment by bradlishman** [comment]
urls.py is an obvious one. I'll dig around a bit and see if I can find a decent overview of the impact between versions.

Ideally, builder would have a dropdown in the first part of the project setup flow where you could select which version you wanted to generate a project for... but that sounds like a lot of effort!

**Comment by fuzzy76** [comment]
I guess it depends on which version most people would like to start a new project in. My guess would be atleast LTS-releases. So just bumping to 1.8 would probably make a lot of sense. And then 1.11 is the next LTS just around the corner...

**Comment by bradlishman** [comment]
Is this complete now? The requirements file generated Django==1.10.3

**Comment by bradlishman** [comment]
![image](https://cloud.githubusercontent.com/assets/2871146/23091872/02c83354-f5c0-11e6-8dcc-ebf61229fa66.png)

Just need to update the homepage. Still shows 1.7
