### ISSUE TITLE
Django Generic Views url issue

### ISSUE THREAD

**Issue by soccer99** [mmcardle/django_builder#25]
Generic detail view ModelDetailView must be called with either an object pk or a slug.

Urls are constructed with `<id>` rather than `<pk>` and cause an issue in the Details view

Django 1.10

**Comment by TeddyBear06** [comment]
+1

**Comment by mmcardle** [comment]
Ill will have look at fixing this. Thanks

**Comment by TeddyBear06** [comment]
I found that in your build (django_builder.min.js) it still switching between slug or or and not pk as you declared in your app ;-)

Probably just need to another build.

**Comment by mmcardle** [comment]
right good spot, ill get another build up!

**Comment by mmcardle** [comment]
Done, might need a hard refresh to see the latest changes
