### ISSUE TITLE
Update of channel settings for redis

### ISSUE THREAD

**Issue by dkdndes** [mmcardle/django_builder#54]
Channel 2.0 Redis support is:

```
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("localhost", 6379)],
        },
    },
}
```
and not as currently stated. Somebody new might activate this option and wonder why it will not work.

**Comment by mmcardle** [comment]
Yes thanks for pointing that out. I'll get it updated

**Comment by dkdndes** [comment]
@mmcardle do you plan to support channels again within version 2. I saw its gone now? Hope its not my Redis question which triggered it.

**Comment by mmcardle** [comment]
@dkdndes Yes i do want to support channels, It is a great app that I use a lot.
I just forgot to port it over in version 2 :)
Will see if I can get something up

**Comment by mmcardle** [comment]
@dkdndes Pushed some changes for channels support
