### ISSUE TITLE
Support Django 2.1?

### ISSUE THREAD

**Issue by huanghe2015** [mmcardle/django_builder#55]
How about the future plan of supporting Django 2.1?

**Comment by mmcardle** [comment]
Yes, this is in the pipeline.
I am currently doing a complete rewrite of the code, which should include the latest django version when it is done.

**Comment by tkovalsky** [comment]
If you’re going to go through these lengths i would be happy to help from a product development perspective 

Have a great day,

Todd Kovalsky

**Comment by mmcardle** [comment]
Thanks for the offer,

I am very close to having a prototype version ready for testing.

**Comment by mmcardle** [comment]
Closing as current version supports django 2+
