### ISSUE TITLE
Allow the django.contrib.auth User and Group models in relation

### ISSUE THREAD

**Issue by brendan-sterne** [mmcardle/django_builder#6]
Love this tool!  

A suggestion: in "Add Relationship" I should be allowed to choose the builtin User and Group models from contrib.auth.

Bonus:  Perhaps even allow the user to choose any model by name (in case I want to connect with other Django apps).

**Comment by mmcardle** [comment]
Thats a great idea, ill try to get it in the next release

**Comment by mmcardle** [comment]
Done
