### ISSUE TITLE
Related Name Is Set to This Field Name as Default

### ISSUE THREAD

**Issue by majid-vaghari** [mmcardle/django_builder#60]
When you define a new foreign key relationship, the builder, automatically assigns the name of this field to [`related_name`](https://docs.djangoproject.com/en/2.1/ref/models/fields/#django.db.models.ForeignKey.related_name) attribute.

This behavior is confusing. Related name is:

> The name to use for the relation from the related object back to this one.

The default behavior of Django is to set it to model name with `_set` suffix. It makes much more sense.

My suggestion is that either you remove setting this attribute when not specified by user or explicitly prompt user for both `related_name` and `related_query_name` properties. In this case you can use Django's default values as placeholders, so the impact on user experience would be low.

**Comment by majid-vaghari** [comment]
Also, when I manually set `related_name` it just adds it along with the default. So it has two `related_name` properties. This seems to be a bug which may be present in other parts of the model builder.

If it's the case, another issue is needed on this mater

**Comment by mmcardle** [comment]
Thanks for the bug report
Working on a fix #62
