### ISSUE TITLE
Use Pipenv

### ISSUE THREAD

**Issue by majid-vaghari** [mmcardle/django_builder#61]
This builder doesn't currently use any package manager. It only lists the requirements in a `requirements.txt` file.

I think it would be good if it used [Pipenv](https://pipenv.readthedocs.io/).

**Comment by mmcardle** [comment]
Hi, 
Thanks for the request.
I don't use pipenv so i would be confident in recommending it to be included automatically, but maybe could provide it as an optional feature when you download?

**Comment by majid-vaghari** [comment]
It could be introduced as an option.

But, IMHO it's a better alternative than `requirements.txt`. I suggest you consider using it for your own projects ;)
