### ISSUE TITLE
Foreign Key Bug

### ISSUE THREAD

**Issue by bglick13** [mmcardle/django_builder#67]
I'm actually not sure if this is a bug with Django or with the django_builder tool, but there's an issue with creating forms with foreign keys.

Specifically, Django (I'm on 2.1.7) has trouble creating forms with foreign keys where the model definition uses strings to define the related field instead of a reference to the related model class. It leads to the following error...

`ValueError: Cannot create form field for '{field_name}' yet, because its related model '{app.related_model}' has not been loaded yet
`

Manually changing the definitions gets around the bug, so maybe that's a solution. I admit that'd probably make automatically generating the code much more difficult as you'd have to resolve the order in which the models are defined. I saw in a previous issue you're currently working on an update for Django 2.1. Is a fix for this already in progress?

Thanks

**Comment by mmcardle** [comment]
Hi @bglick13 yes this is something that is mostly sorted out in the new version, I say `mostly` because you can make circular relationships which are hard to generate code for. Hopefully releasing an updated version soon.

**Comment by bglick13** [comment]
Awesome, thanks for the response(s)! I'm looking forward to checking out the new version.

By the way, if you are open to/looking for collaborators I'd be happy to participate. This really is an awesome tool

**Comment by mmcardle** [comment]
New version pushed.
