### ISSUE TITLE
Source mismatch between the repo and djangobuilder.io?

### ISSUE THREAD

**Issue by darkpixel** [mmcardle/django_builder#79]
https://djangobuilder.io appears to support Django 2.1.x.

When I go to to the About page and follow the github link, it takes me to this repo.  Cloning this repo and running it locally gives me a version that supports 2.0 and recommends I try https://djangobuilder.io.

Am I missing something, or is the latest source not available yet?

**Comment by mmcardle** [comment]
Hi @darkpixel 

Correct i haven't got round to publishing the source for https://djangobuilder.io
There are still a few steps i need to do to make it fit for consumption :)

**Comment by darkpixel** [comment]
No worries--thanks!

**Comment by smeggingsmegger** [comment]
@mmcardle I would love to contribute when you do. Excellent project!

**Comment by mmcardle** [comment]
I have just pushed the source for version 2 djangobuilder.io 
Note: it requires a Firebase account

**Comment by mmcardle** [comment]
Closing as this is now complete
