### ISSUE TITLE
Adding Relationship between models such as ForeignKey inserts "undefined" in source code

### ISSUE THREAD

**Issue by ranjanprj** [mmcardle/django_builder#81]
First of all really great tool for us beginner
When I add a simple ForeignKey relationship between two models
![image](https://user-images.githubusercontent.com/15071992/76398860-a0fd5f00-63a3-11ea-8338-d84361b0156e.png)

The source code generated has the word "undefined" before the model name in models.py
![image](https://user-images.githubusercontent.com/15071992/76398775-81663680-63a3-11ea-885a-ce284208029e.png)

I believe this is due to JavaScript issue

**Comment by mmcardle** [comment]
@ranjanprj glad you like the tool

Yes that looks like a bug, i will see if i can get it fixed!

**Comment by mmcardle** [comment]
This should be fixed now. try refreshing your browser.
