### ISSUE TITLE
User imported as string in models

### ISSUE THREAD

**Issue by maxtheman** [mmcardle/django_builder#9]
When creating user foreignkeys, Django Builder creates code like

`class Employee(models.Model):
    user = models.OneToOneField('django.contrib.auth.models.user', on_delete=models.CASCADE)`

This can cause weird errors and doesn't import User correctly anyway. The "right" output would be:

`from django.contrib.auth.models import User

class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)`

**Comment by mmcardle** [comment]
Thanks for the info, ill get a fix for that.

Was this importing a models.py or manually creating the models?

**Comment by maxtheman** [comment]
It was manually creating. You should be able to reproduce using the
deployed site.

**Comment by mmcardle** [comment]
@maxtheman  I would like to fix this but I am struggling to reproduce it.

What browser are you using?
Can you recreate from a clean django builder app, and list the steps to reproduce?

Thanks

**Comment by maxtheman** [comment]
I am unable to reproduce it now. Sorry for the false alarm, let's chalk it up to user error. :-)
